# Generated by Django 6.0.1 on 2026-01-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_fooditem_is_special'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('offer_code', models.CharField(max_length=10, unique=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemOfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditem')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.offerdiscount')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemcategory')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.offerdiscount')),
            ],
        ),
    ]
