# Generated by Django 6.0.1 on 2026-01-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='date',
            new_name='added_on',
        ),
    ]
