# Generated by Django 6.0.1 on 2026-01-24 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_fooditem_is_special'),
        ('orders', '0003_rename_date_wishlist_added_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='customer',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'food_item')},
        ),
    ]
