# Generated by Django 6.0.1 on 2026-01-24 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_offerapply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditemofferdiscount',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='fooditemofferdiscount',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='offerapply',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offerapply',
            name='food_item',
        ),
        migrations.RemoveField(
            model_name='offerapply',
            name='offer',
        ),
        migrations.AddField(
            model_name='offerdiscount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerdiscount',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='offerdiscount',
            name='offer_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='CategoryOfferDiscount',
        ),
        migrations.DeleteModel(
            name='FoodItemOfferDiscount',
        ),
        migrations.DeleteModel(
            name='OfferApply',
        ),
    ]
