# Generated by Django 6.0.1 on 2026-01-24 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_fooditem_is_special'),
        ('orders', '0004_remove_fooditemofferdiscount_food_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryOfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemcategory')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.offerdiscount')),
            ],
        ),
        migrations.CreateModel(
            name='FoodItemOfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditem')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.offerdiscount')),
            ],
        ),
    ]
