# Generated by Django 6.0.1 on 2026-01-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_customer_wishlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='added_on',
            new_name='added_date',
        ),
    ]
