# Generated by Django 6.0.1 on 2026-01-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_offerapply_categoryofferdiscount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferApply',
        ),
    ]
