# Generated by Django 6.0.1 on 2026-01-24 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_fooditem_price'),
        ('orders', '0006_delete_offerapply'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemofferdiscount',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemcategory'),
        ),
    ]
