# Generated by Django 6.0.1 on 2026-01-25 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_fooditem_price'),
        ('orders', '0007_fooditemofferdiscount_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryOfferDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.offerdiscount')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.fooditemsubcategory')),
            ],
        ),
    ]
