# Generated by Django 6.0.1 on 2026-01-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_subcategoryofferdiscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdiscount',
            old_name='isactive',
            new_name='is_active',
        ),
    ]
