# Generated by Django 6.0.1 on 2026-01-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_isactive_offerdiscount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdiscount',
            old_name='is_active',
            new_name='isactive',
        ),
    ]
