# Generated by Django 6.0.1 on 2026-01-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_added_on_wishlist_added_date'),
        ('orders', '0010_rename_is_active_offerdiscount_isactive'),
    ]

    operations = [
    ]
