# Generated by Django 6.0.1 on 2026-01-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
