# Generated by Django 6.0.1 on 2026-02-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_merge_20260126_1759'),
        ('orders', '0016_wishlist'),
    ]

    operations = [
    ]
