# Generated by Django 6.0.1 on 2026-01-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contactno', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('isadmin', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('updationdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
