# Generated by Django 6.0.1 on 2026-01-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_alter_customer_managers_and_more'),
        ('accounts', '0002_customer_is_delivery_person'),
    ]

    operations = [
    ]
