# Generated by Django 6.0.1 on 2026-02-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_passwordresetotp_attempts_alter_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
