# Generated by Django 6.0.1 on 2026-01-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='delivery_person_id',
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='deliveryperson',
            name='lname',
            field=models.CharField(max_length=30),
        ),
    ]
