# Generated by Django 6.0.1 on 2026-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypanel', '0002_remove_deliveryperson_delivery_person_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
