# Generated by Django 6.0.1 on 2026-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypanel', '0003_deliveryperson_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryperson',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='delivery/profile_pics/'),
        ),
    ]
