# Generated by Django 6.0.1 on 2026-02-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverypanel', '0004_deliveryperson_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Scooter', 'Scooter')], max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('delivery_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='deliverypanel.deliveryperson')),
            ],
        ),
    ]
